### ISSUE TITLE
Node functions arguments

### ISSUE THREAD

**Issue by jpiabrantes** [eBay/bayesian-belief-networks#12]
When a node function as its arguments wrong or misspelled no exception is thrown, the program just takes forever to build the bbn and doesn't give any feedback to the user to what's going wrong. 

P.S. It would be nice to allow the functions to have the argument "self" so they could be methods of classes.

**Comment by nnewey** [comment]
A new method (validate_keyvals) has been added which is called from .query() that will throw an Exception if an invalid variable name of value is supplied to .query()
