### ISSUE TITLE
Inference of Graph Structure from Mass Function

### ISSUE THREAD

**Issue by ijosc** [eBay/bayesian-belief-networks#14]
In the readme file under "other features" you write that we can do "Inference of Graph Structure from Mass Functions" using this package. I have been going through the examples and the code but wasn't able to find out how I would go about doing that.

Any help would be greatly appreciated:)

**Comment by nnewey** [comment]
Hi Johannes

What that refers to is the fact that the graph structure of the model does not have to be explicitly specified. It is implied by the mass functions themselves and "inferred" in the sense that the internal graph structure is constructed by examining the mass functions and their arguments. The author of the model thus does not have to build a graph with nodes and edges. The framework does however allow you to explicitly construct the graph if you would so prefer.

**Comment by ijosc** [comment]
Thanks for the answer @nnewey !
I thought it meant that the package can infer graph structure from data, i.e. find causal relations between variables by for example doing maximum a posteriori probability estimation. I will fork this repo and see whether I can implement this myself.

**Comment by nnewey** [comment]
Great, thank you, the functionality you describe is one of the longer term goals, but it is not being actively worked on so your help is very much appreciated!

**Comment by ijosc** [comment]
@nnewey 
I have started with this project of inferring graph structure from data with this package and I am seeing some issues that I am not sure how to overcome. Would you be willing to exchange some emails to talk about this? My email address is in my profile.
