### ISSUE TITLE
make html not working

### ISSUE THREAD

**Issue by hvandenb** [eBay/bayesian-belief-networks#16]
When running in virtualenv the installation works, but when I get to the html build the following error happens.

> commit 511856960e87e070748db5bac7d59ddd1bb5b1e0
> 
> sphinx-build -b html -d _build/doctrees   . _build/html
> Running Sphinx v1.4.1
> making output directory...
> WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.
> 
> Extension error:
> Config value 'math_number_all' already present
> make: **\* [html] Error 1

**Comment by catfalls** [comment]
I encounter the same problem.

**Comment by catfalls** [comment]
I solved this problem by commenting out 'sphinx.ext.imgmath'. My modification in `conf.py`：
```
extensions = [
# 'sphinx.ext.imgmath',
'sphinx.ext.mathjax', 'sphinx.ext.viewcode']
```

**Comment by nnewey** [comment]
Updated conf.py
