### ISSUE TITLE
There is something wrong when I get the graph of Junction Tree by function get_graphviz_source()

### ISSUE THREAD

**Issue by liupei101** [eBay/bayesian-belief-networks#20]
In function ''get_graphviz_source()' of class JoinTree, we can get dot file which can be transformed into picture by Graphviz, but when some sepset_nodes which have same name occured,we will get inconsistent one. This really Influenced watching,so please think about it.
 THX!!!

**Comment by liupei101** [comment]
## The following is the result of running cancer.py:
![jtgraph](https://cloud.githubusercontent.com/assets/15051403/23493888/1d7b4356-ff4a-11e6-8a6a-a7a6cddee513.png)
## Obviously, Because of two same name sep_node,the picture is theoretically inconsistent.
## And the picture we should get is:
![jtgraph](https://cloud.githubusercontent.com/assets/15051403/23493843/c8e9a666-ff49-11e6-84d2-84cf9bc52ec9.png)

**Comment by nnewey** [comment]
This is now fixed, here is the resulting image:
![cancer_jt](https://user-images.githubusercontent.com/4682876/28887752-2b625fc6-7773-11e7-93cf-fdf5ae1f2d29.png)
