### ISSUE TITLE
Extension error: sphinx.ext.mathjax: other math package is already loaded

### ISSUE THREAD

**Issue by abitofalchemy** [eBay/bayesian-belief-networks#21]
Extension error:
sphinx.ext.mathjax: other math package is already loaded
make: *** [html] Error 1

How do I bypass or get around this error?

**Comment by arbenton** [comment]
As a workaround, remove `sphinx.ext.pngmath` from the list `extensions` in "docs/tutorial/conf.py".

I'm not sure what side effects this may have, but it will atleast compile.

**Comment by nnewey** [comment]
This has been fixed in conf.py now.
